function makeBeersArray() {
    return [
        {
            brewery_id: 1234567,
            name: 'Munsterfest',
            cat_id: 1234567,
            style_id: 123456,
            abv: 4.95,
            ibu: 2.00,
            srm: 2.00,
            upc: 12345678,
            filepath: 'none',
            description: 'solid beer',
            add_user: 0,
            last_mod: '2029-01-22'
            
        },
        {
            brewery_id: 1234567,
            name: 'gumballhead',
            cat_id: 1234568,
            style_id: 123458,
            abv: 4.85,
            ibu: 2.00,
            srm: 2.00,
            upc: 12345679,
            filepath: 'none',
            description: 'ok beer',
            add_user: 0,
            last_mod: '2029-01-22'
            
        },
        {
            brewery_id: 1234567,
            name: 'lagunitas ipa',
            cat_id: 1234569,
            style_id: 123459,
            abv: 6.95,
            ibu: 2.00,
            srm: 2.00,
            upc: 12345676,
            filepath: 'none',
            description: 'great beer',
            add_user: 0,
            last_mod: '2029-01-22'
            
        },
    ]
}




// CREATE TABLE beers (
//     id integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
//     brewery_id integer NOT NULL default '0',
//     name text not null,
//     cat_id integer NOT NULL default '0',
//     style_id integer NOT NULL default '0',
//     abv float NOT NULL default '0',
//     ibu float NOT NULL default '0',
//     srm float NOT NULL default '0',
//     upc integer NOT NULL default '0',
//     filepath text,
//     descript text,
//     add_user integer NOT NULL default '0',
//     last_mod TIMESTAMP DEFAULT now() NOT NULL
//   );
  