CREATE TABLE beers (
  id integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  brewery_id integer NOT NULL default '0',
  name text not null,
  cat_id integer NOT NULL default '0',
  style_id integer NOT NULL default '0',
  abv float NOT NULL default '0',
  ibu float NOT NULL default '0',
  srm float NOT NULL default '0',
  upc integer NOT NULL default '0',
  filepath text,
  descript text,
  add_user integer NOT NULL default '0',
  last_mod TIMESTAMPTZ DEFAULT now() NOT NULL
);
